@echo off

echo Starting database...
docker compose up -d

echo Waiting for DB to initialize...
timeout /t 10 /nobreak

echo Launching frontend...
start cmd /k "cd frontend && npm run dev"

echo Starting backend...
npm run dev